In [40]:
import pandas as pd
import numpy as np
df  = pd.read_csv("student.csv")

In [41]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-02-06
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2023-12-17
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-08
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-28
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-14
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2024-01-22
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2023-12-17
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-02-13
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-01-05
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-17
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2023-12-27
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2024-02-11
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2024-01-06
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-28
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-01-09
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-02-02
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-11
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-02-12
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2024-01-26
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-12

In [42]:
df['คณะ'].fillna(df['คณะ'].mode()[0], inplace=True)
print(df)

    รหัสนักศึกษา      ชื่อ   อายุ     เพศ             คณะ   GPA  ส่วนสูง_cm  \
0          64001     สมชาย   20.0     ชาย     วิทยาศาสตร์  3.21       170.0
1          64002    สมหญิง   21.0    หญิง           วิทย์  3.45       165.0
2          64003       NaN    NaN    Male         Science  3.67       175.0
3          64004  สมศักดิ์   22.0       ช  คณะวิทยาศาสตร์ -1.00       168.0
4          64005      สมใจ   19.0       ญ           วิศวะ  3.89       160.0
5          64006     กานต์  150.0     ชาย     Engineering  3.12       172.0
6          64007     กิตติ   21.0    หญิง        วิศวกรรม  4.50       158.0
7          64008      จิรา   20.0       F      ศิลปศาสตร์  2.98       180.0
8          64009    ชนาธิป   23.0       M            Arts  3.34       163.0
9          64010      ดารา   21.0    หญิง           ศิลป์  3.56       167.0
10         64011      ธีระ    NaN     NaN         Science  3.78         NaN
11         64012       นภา   22.0     ชาย           วิทย์   NaN       171.0
12         64013     บุญมี   20.0    หญิง           วิศวฯ  3.23       169.0
13         64014     ปรีชา   21.0     ชาย    Liberal Arts  3.45       164.0
14         64015     พิมพ์   22.0  Female             Sci  3.67       162.0
15         64016      ภูมิ   19.0       ช     วิทยาศาสตร์  3.89       173.0
16         64017      มานี   20.0       ญ  วิศวกรรมศาสตร์  3.01       166.0
17         64018      ยุพา   21.0    หญิง         Science  3.23       161.0
18         64019     รัตนา    NaN     ชาย      ศิลปศาสตร์   NaN       174.0
19         64020     ลัดดา   22.0     NaN         Science  3.45       168.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0         65.0                     15.0      2024-02-06
1         58.0                     20.0      2023-12-17
2          NaN                     25.0      2024-01-08
3         70.0                     10.0      2024-01-28
4         52.0                     30.0      2024-01-14
5         75.0                     12.0      2024-01-22
6         48.0                     35.0      2023-12-17
7         82.0                     18.0      2024-02-13
8         55.0                     22.0      2024-01-05
9         60.0                     28.0      2024-01-17
10        68.0                      NaN      2023-12-27
11         NaN                     16.0      2024-02-11
12        72.0                     24.0      2024-01-06
13        54.0                     19.0      2024-01-28
14        56.0                     26.0      2024-01-09
15        78.0                     14.0      2024-02-02
16        62.0                     21.0      2024-01-11
17        50.0                     27.0      2024-02-12
18        76.0                      NaN      2024-01-26
19        64.0                     23.0      2024-01-12

/tmp/ipython-input-711902885.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['คณะ'].fillna(df['คณะ'].mode()[0], inplace=True)

In [43]:
def standardize_faculty(คณะ):
    if คณะ in ['วิทยาศาสตร์', 'คณะวิทยาศาสตร์', 'วิทย์', 'Science', 'Sci']:
        return 'วิทยาศาสตร์'
    elif คณะ in ['วิศวกรรมศาสตร์', 'วิศวกรรม', 'วิศวฯ', 'วิศวะ', 'Engineering']:
        return 'วิศวกรรมศาสตร์'
    elif คณะ in ['ศิลปศาสตร์', 'ศิลป์', 'Liberal Arts', 'Arts']:
        return 'ศิลปศาสตร์'
    else:
        return คณะ

df['คณะ'] = df['คณะ'].apply(standardize_faculty)
df['คณะ'].fillna(df['คณะ'].mode()[0], inplace=True)
df

/tmp/ipython-input-772493833.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['คณะ'].fillna(df['คณะ'].mode()[0], inplace=True)

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-02-06
1,64002,สมหญิง,21.0,หญิง,วิทยาศาสตร์,3.45,165.0,58.0,20.0,2023-12-17
2,64003,NaN,NaN,Male,วิทยาศาสตร์,3.67,175.0,NaN,25.0,2024-01-08
3,64004,สมศักดิ์,22.0,ช,วิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-28
4,64005,สมใจ,19.0,ญ,วิศวกรรมศาสตร์,3.89,160.0,52.0,30.0,2024-01-14
5,64006,กานต์,150.0,ชาย,วิศวกรรมศาสตร์,3.12,172.0,75.0,12.0,2024-01-22
6,64007,กิตติ,21.0,หญิง,วิศวกรรมศาสตร์,4.50,158.0,48.0,35.0,2023-12-17
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-02-13
8,64009,ชนาธิป,23.0,M,ศิลปศาสตร์,3.34,163.0,55.0,22.0,2024-01-05
9,64010,ดารา,21.0,หญิง,ศิลปศาสตร์,3.56,167.0,60.0,28.0,2024-01-17
10,64011,ธีระ,NaN,NaN,วิทยาศาสตร์,3.78,NaN,68.0,NaN,2023-12-27
11,64012,นภา,22.0,ชาย,วิทยาศาสตร์,NaN,171.0,NaN,16.0,2024-02-11
12,64013,บุญมี,20.0,หญิง,วิศวกรรมศาสตร์,3.23,169.0,72.0,24.0,2024-01-06
13,64014,ปรีชา,21.0,ชาย,ศิลปศาสตร์,3.45,164.0,54.0,19.0,2024-01-28
14,64015,พิมพ์,22.0,Female,วิทยาศาสตร์,3.67,162.0,56.0,26.0,2024-01-09
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-02-02
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-11
17,64018,ยุพา,21.0,หญิง,วิทยาศาสตร์,3.23,161.0,50.0,27.0,2024-02-12
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2024-01-26
19,64020,ลัดดา,22.0,NaN,วิทยาศาสตร์,3.45,168.0,64.0,23.0,2024-01-12

In [44]:
def standardize_faculty(เพศ):
    if เพศ in ['ชาย', 'ช', 'Male', 'M']:
        return 'ชาย'
    elif เพศ in ['หญิง', 'ญ', 'Female', 'F']:
        return 'หญิง'
    else:
        return เพศ

df['เพศ'] = df['เพศ'].apply(standardize_faculty)
df['เพศ'].fillna(df['เพศ'].mode()[0], inplace=True)
df

/tmp/ipython-input-18236220.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['เพศ'].fillna(df['เพศ'].mode()[0], inplace=True)

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-02-06
1,64002,สมหญิง,21.0,หญิง,วิทยาศาสตร์,3.45,165.0,58.0,20.0,2023-12-17
2,64003,NaN,NaN,ชาย,วิทยาศาสตร์,3.67,175.0,NaN,25.0,2024-01-08
3,64004,สมศักดิ์,22.0,ชาย,วิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-28
4,64005,สมใจ,19.0,หญิง,วิศวกรรมศาสตร์,3.89,160.0,52.0,30.0,2024-01-14
5,64006,กานต์,150.0,ชาย,วิศวกรรมศาสตร์,3.12,172.0,75.0,12.0,2024-01-22
6,64007,กิตติ,21.0,หญิง,วิศวกรรมศาสตร์,4.50,158.0,48.0,35.0,2023-12-17
7,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-02-13
8,64009,ชนาธิป,23.0,ชาย,ศิลปศาสตร์,3.34,163.0,55.0,22.0,2024-01-05
9,64010,ดารา,21.0,หญิง,ศิลปศาสตร์,3.56,167.0,60.0,28.0,2024-01-17
10,64011,ธีระ,NaN,ชาย,วิทยาศาสตร์,3.78,NaN,68.0,NaN,2023-12-27
11,64012,นภา,22.0,ชาย,วิทยาศาสตร์,NaN,171.0,NaN,16.0,2024-02-11
12,64013,บุญมี,20.0,หญิง,วิศวกรรมศาสตร์,3.23,169.0,72.0,24.0,2024-01-06
13,64014,ปรีชา,21.0,ชาย,ศิลปศาสตร์,3.45,164.0,54.0,19.0,2024-01-28
14,64015,พิมพ์,22.0,หญิง,วิทยาศาสตร์,3.67,162.0,56.0,26.0,2024-01-09
15,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-02-02
16,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-11
17,64018,ยุพา,21.0,หญิง,วิทยาศาสตร์,3.23,161.0,50.0,27.0,2024-02-12
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2024-01-26
19,64020,ลัดดา,22.0,ชาย,วิทยาศาสตร์,3.45,168.0,64.0,23.0,2024-01-12

In [45]:
Q1 = df['อายุ'].quantile(0.25)
Q3 = df['อายุ'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df_no_outliers = df[(df['อายุ'] >= lower_bound) & (df['อายุ'] <= upper_bound) &
                    (df['อายุ'] >= 18) & (df['อายุ'] <= 23)]

mean_age = df_no_outliers['อายุ'].mean()

df['อายุ'].fillna(mean_age, inplace=True)

df.loc[(df['อายุ'] < 18) | (df['อายุ'] > 23), 'อายุ'] = mean_age
df

/tmp/ipython-input-128230514.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['อายุ'].fillna(mean_age, inplace=True)

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-02-06
1,64002,สมหญิง,21.000,หญิง,วิทยาศาสตร์,3.45,165.0,58.0,20.0,2023-12-17
2,64003,NaN,20.875,ชาย,วิทยาศาสตร์,3.67,175.0,NaN,25.0,2024-01-08
3,64004,สมศักดิ์,22.000,ชาย,วิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-28
4,64005,สมใจ,19.000,หญิง,วิศวกรรมศาสตร์,3.89,160.0,52.0,30.0,2024-01-14
5,64006,กานต์,20.875,ชาย,วิศวกรรมศาสตร์,3.12,172.0,75.0,12.0,2024-01-22
6,64007,กิตติ,21.000,หญิง,วิศวกรรมศาสตร์,4.50,158.0,48.0,35.0,2023-12-17
7,64008,จิรา,20.000,หญิง,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-02-13
8,64009,ชนาธิป,23.000,ชาย,ศิลปศาสตร์,3.34,163.0,55.0,22.0,2024-01-05
9,64010,ดารา,21.000,หญิง,ศิลปศาสตร์,3.56,167.0,60.0,28.0,2024-01-17
10,64011,ธีระ,20.875,ชาย,วิทยาศาสตร์,3.78,NaN,68.0,NaN,2023-12-27
11,64012,นภา,22.000,ชาย,วิทยาศาสตร์,NaN,171.0,NaN,16.0,2024-02-11
12,64013,บุญมี,20.000,หญิง,วิศวกรรมศาสตร์,3.23,169.0,72.0,24.0,2024-01-06
13,64014,ปรีชา,21.000,ชาย,ศิลปศาสตร์,3.45,164.0,54.0,19.0,2024-01-28
14,64015,พิมพ์,22.000,หญิง,วิทยาศาสตร์,3.67,162.0,56.0,26.0,2024-01-09
15,64016,ภูมิ,19.000,ชาย,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-02-02
16,64017,มานี,20.000,หญิง,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-11
17,64018,ยุพา,21.000,หญิง,วิทยาศาสตร์,3.23,161.0,50.0,27.0,2024-02-12
18,64019,รัตนา,20.875,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2024-01-26
19,64020,ลัดดา,22.000,ชาย,วิทยาศาสตร์,3.45,168.0,64.0,23.0,2024-01-12

In [46]:
print(f"- GPA ผิดปกติ - {df[(df['GPA'] < 0) | (df['GPA'] > 4)]['GPA'].tolist()}")

mean_gpa = df['GPA'].mean()

df.loc[df['GPA'] < 0, 'GPA'] = np.nan
df.loc[df['GPA'] > 4, 'GPA'] = 4.0

df['GPA'].fillna(mean_gpa, inplace=True)
df

/tmp/ipython-input-1743627993.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['GPA'].fillna(mean_gpa, inplace=True)

- GPA ผิดปกติ - [-1.0, 4.5]

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000,ชาย,วิทยาศาสตร์,3.210000,170.0,65.0,15.0,2024-02-06
1,64002,สมหญิง,21.000,หญิง,วิทยาศาสตร์,3.450000,165.0,58.0,20.0,2023-12-17
2,64003,NaN,20.875,ชาย,วิทยาศาสตร์,3.670000,175.0,NaN,25.0,2024-01-08
3,64004,สมศักดิ์,22.000,ชาย,วิทยาศาสตร์,3.246111,168.0,70.0,10.0,2024-01-28
4,64005,สมใจ,19.000,หญิง,วิศวกรรมศาสตร์,3.890000,160.0,52.0,30.0,2024-01-14
5,64006,กานต์,20.875,ชาย,วิศวกรรมศาสตร์,3.120000,172.0,75.0,12.0,2024-01-22
6,64007,กิตติ,21.000,หญิง,วิศวกรรมศาสตร์,4.000000,158.0,48.0,35.0,2023-12-17
7,64008,จิรา,20.000,หญิง,ศิลปศาสตร์,2.980000,180.0,82.0,18.0,2024-02-13
8,64009,ชนาธิป,23.000,ชาย,ศิลปศาสตร์,3.340000,163.0,55.0,22.0,2024-01-05
9,64010,ดารา,21.000,หญิง,ศิลปศาสตร์,3.560000,167.0,60.0,28.0,2024-01-17
10,64011,ธีระ,20.875,ชาย,วิทยาศาสตร์,3.780000,NaN,68.0,NaN,2023-12-27
11,64012,นภา,22.000,ชาย,วิทยาศาสตร์,3.246111,171.0,NaN,16.0,2024-02-11
12,64013,บุญมี,20.000,หญิง,วิศวกรรมศาสตร์,3.230000,169.0,72.0,24.0,2024-01-06
13,64014,ปรีชา,21.000,ชาย,ศิลปศาสตร์,3.450000,164.0,54.0,19.0,2024-01-28
14,64015,พิมพ์,22.000,หญิง,วิทยาศาสตร์,3.670000,162.0,56.0,26.0,2024-01-09
15,64016,ภูมิ,19.000,ชาย,วิทยาศาสตร์,3.890000,173.0,78.0,14.0,2024-02-02
16,64017,มานี,20.000,หญิง,วิศวกรรมศาสตร์,3.010000,166.0,62.0,21.0,2024-01-11
17,64018,ยุพา,21.000,หญิง,วิทยาศาสตร์,3.230000,161.0,50.0,27.0,2024-02-12
18,64019,รัตนา,20.875,ชาย,ศิลปศาสตร์,3.246111,174.0,76.0,NaN,2024-01-26
19,64020,ลัดดา,22.000,ชาย,วิทยาศาสตร์,3.450000,168.0,64.0,23.0,2024-01-12

In [47]:
max_height = df['ส่วนสูง_cm'].max()
min_height = df['ส่วนสูง_cm'].min()

print(f"ส่วนสูง_cm: สูงสุด = {max_height}, ต่ำสุด = {min_height}")

mean_cm = df['ส่วนสูง_cm'].mean()

df['ส่วนสูง_cm'].fillna(mean_cm, inplace=True)
df

ส่วนสูง_cm: สูงสุด = 180.0, ต่ำสุด = 158.0

/tmp/ipython-input-3702223871.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ส่วนสูง_cm'].fillna(mean_cm, inplace=True)

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.0,15.0,2024-02-06
1,64002,สมหญิง,21.000,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.0,20.0,2023-12-17
2,64003,NaN,20.875,ชาย,วิทยาศาสตร์,3.670000,175.000000,NaN,25.0,2024-01-08
3,64004,สมศักดิ์,22.000,ชาย,วิทยาศาสตร์,3.246111,168.000000,70.0,10.0,2024-01-28
4,64005,สมใจ,19.000,หญิง,วิศวกรรมศาสตร์,3.890000,160.000000,52.0,30.0,2024-01-14
5,64006,กานต์,20.875,ชาย,วิศวกรรมศาสตร์,3.120000,172.000000,75.0,12.0,2024-01-22
6,64007,กิตติ,21.000,หญิง,วิศวกรรมศาสตร์,4.000000,158.000000,48.0,35.0,2023-12-17
7,64008,จิรา,20.000,หญิง,ศิลปศาสตร์,2.980000,180.000000,82.0,18.0,2024-02-13
8,64009,ชนาธิป,23.000,ชาย,ศิลปศาสตร์,3.340000,163.000000,55.0,22.0,2024-01-05
9,64010,ดารา,21.000,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.0,28.0,2024-01-17
10,64011,ธีระ,20.875,ชาย,วิทยาศาสตร์,3.780000,167.684211,68.0,NaN,2023-12-27
11,64012,นภา,22.000,ชาย,วิทยาศาสตร์,3.246111,171.000000,NaN,16.0,2024-02-11
12,64013,บุญมี,20.000,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.0,24.0,2024-01-06
13,64014,ปรีชา,21.000,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.0,19.0,2024-01-28
14,64015,พิมพ์,22.000,หญิง,วิทยาศาสตร์,3.670000,162.000000,56.0,26.0,2024-01-09
15,64016,ภูมิ,19.000,ชาย,วิทยาศาสตร์,3.890000,173.000000,78.0,14.0,2024-02-02
16,64017,มานี,20.000,หญิง,วิศวกรรมศาสตร์,3.010000,166.000000,62.0,21.0,2024-01-11
17,64018,ยุพา,21.000,หญิง,วิทยาศาสตร์,3.230000,161.000000,50.0,27.0,2024-02-12
18,64019,รัตนา,20.875,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.0,NaN,2024-01-26
19,64020,ลัดดา,22.000,ชาย,วิทยาศาสตร์,3.450000,168.000000,64.0,23.0,2024-01-12

In [48]:
max_weight = df['น้ำหนัก_kg'].max()
min_weight = df['น้ำหนัก_kg'].min()

print(f"น้ำหนัก_kg: สูงสุด = {max_weight}, ต่ำสุด = {min_weight}")

mean_wt = df['น้ำหนัก_kg'].mean()

df['น้ำหนัก_kg'].fillna(mean_wt, inplace=True)
df

/tmp/ipython-input-3233656744.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['น้ำหนัก_kg'].fillna(mean_wt, inplace=True)

น้ำหนัก_kg: สูงสุด = 82.0, ต่ำสุด = 48.0

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.0,2024-02-06
1,64002,สมหญิง,21.000,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.000000,20.0,2023-12-17
2,64003,NaN,20.875,ชาย,วิทยาศาสตร์,3.670000,175.000000,63.611111,25.0,2024-01-08
3,64004,สมศักดิ์,22.000,ชาย,วิทยาศาสตร์,3.246111,168.000000,70.000000,10.0,2024-01-28
4,64005,สมใจ,19.000,หญิง,วิศวกรรมศาสตร์,3.890000,160.000000,52.000000,30.0,2024-01-14
5,64006,กานต์,20.875,ชาย,วิศวกรรมศาสตร์,3.120000,172.000000,75.000000,12.0,2024-01-22
6,64007,กิตติ,21.000,หญิง,วิศวกรรมศาสตร์,4.000000,158.000000,48.000000,35.0,2023-12-17
7,64008,จิรา,20.000,หญิง,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.0,2024-02-13
8,64009,ชนาธิป,23.000,ชาย,ศิลปศาสตร์,3.340000,163.000000,55.000000,22.0,2024-01-05
9,64010,ดารา,21.000,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.000000,28.0,2024-01-17
10,64011,ธีระ,20.875,ชาย,วิทยาศาสตร์,3.780000,167.684211,68.000000,NaN,2023-12-27
11,64012,นภา,22.000,ชาย,วิทยาศาสตร์,3.246111,171.000000,63.611111,16.0,2024-02-11
12,64013,บุญมี,20.000,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.000000,24.0,2024-01-06
13,64014,ปรีชา,21.000,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.000000,19.0,2024-01-28
14,64015,พิมพ์,22.000,หญิง,วิทยาศาสตร์,3.670000,162.000000,56.000000,26.0,2024-01-09
15,64016,ภูมิ,19.000,ชาย,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.0,2024-02-02
16,64017,มานี,20.000,หญิง,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.0,2024-01-11
17,64018,ยุพา,21.000,หญิง,วิทยาศาสตร์,3.230000,161.000000,50.000000,27.0,2024-02-12
18,64019,รัตนา,20.875,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,NaN,2024-01-26
19,64020,ลัดดา,22.000,ชาย,วิทยาศาสตร์,3.450000,168.000000,64.000000,23.0,2024-01-12

In [49]:
max_hours = df['ชั่วโมงเรียน_ต่อสัปดาห์'].max()
min_hours = df['ชั่วโมงเรียน_ต่อสัปดาห์'].min()

print(f"ชั่วโมงเรียน_ต่อสัปดาห์: สูงสุด = {max_hours}, ต่ำสุด = {min_hours}")

mean_hr = df['ชั่วโมงเรียน_ต่อสัปดาห์'].mean()

df['ชั่วโมงเรียน_ต่อสัปดาห์'].fillna(mean_hr, inplace=True)
df

/tmp/ipython-input-3086008830.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ชั่วโมงเรียน_ต่อสัปดาห์'].fillna(mean_hr, inplace=True)

ชั่วโมงเรียน_ต่อสัปดาห์: สูงสุด = 35.0, ต่ำสุด = 10.0

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.000000,2024-02-06
1,64002,สมหญิง,21.000,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.000000,20.000000,2023-12-17
2,64003,NaN,20.875,ชาย,วิทยาศาสตร์,3.670000,175.000000,63.611111,25.000000,2024-01-08
3,64004,สมศักดิ์,22.000,ชาย,วิทยาศาสตร์,3.246111,168.000000,70.000000,10.000000,2024-01-28
4,64005,สมใจ,19.000,หญิง,วิศวกรรมศาสตร์,3.890000,160.000000,52.000000,30.000000,2024-01-14
5,64006,กานต์,20.875,ชาย,วิศวกรรมศาสตร์,3.120000,172.000000,75.000000,12.000000,2024-01-22
6,64007,กิตติ,21.000,หญิง,วิศวกรรมศาสตร์,4.000000,158.000000,48.000000,35.000000,2023-12-17
7,64008,จิรา,20.000,หญิง,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.000000,2024-02-13
8,64009,ชนาธิป,23.000,ชาย,ศิลปศาสตร์,3.340000,163.000000,55.000000,22.000000,2024-01-05
9,64010,ดารา,21.000,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.000000,28.000000,2024-01-17
10,64011,ธีระ,20.875,ชาย,วิทยาศาสตร์,3.780000,167.684211,68.000000,21.388889,2023-12-27
11,64012,นภา,22.000,ชาย,วิทยาศาสตร์,3.246111,171.000000,63.611111,16.000000,2024-02-11
12,64013,บุญมี,20.000,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.000000,24.000000,2024-01-06
13,64014,ปรีชา,21.000,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.000000,19.000000,2024-01-28
14,64015,พิมพ์,22.000,หญิง,วิทยาศาสตร์,3.670000,162.000000,56.000000,26.000000,2024-01-09
15,64016,ภูมิ,19.000,ชาย,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.000000,2024-02-02
16,64017,มานี,20.000,หญิง,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.000000,2024-01-11
17,64018,ยุพา,21.000,หญิง,วิทยาศาสตร์,3.230000,161.000000,50.000000,27.000000,2024-02-12
18,64019,รัตนา,20.875,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,21.388889,2024-01-26
19,64020,ลัดดา,22.000,ชาย,วิทยาศาสตร์,3.450000,168.000000,64.000000,23.000000,2024-01-12

# **ข้อมูลหลัง Clean Data**

In [50]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.000000,2024-02-06
1,64002,สมหญิง,21.000,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.000000,20.000000,2023-12-17
2,64003,NaN,20.875,ชาย,วิทยาศาสตร์,3.670000,175.000000,63.611111,25.000000,2024-01-08
3,64004,สมศักดิ์,22.000,ชาย,วิทยาศาสตร์,3.246111,168.000000,70.000000,10.000000,2024-01-28
4,64005,สมใจ,19.000,หญิง,วิศวกรรมศาสตร์,3.890000,160.000000,52.000000,30.000000,2024-01-14
5,64006,กานต์,20.875,ชาย,วิศวกรรมศาสตร์,3.120000,172.000000,75.000000,12.000000,2024-01-22
6,64007,กิตติ,21.000,หญิง,วิศวกรรมศาสตร์,4.000000,158.000000,48.000000,35.000000,2023-12-17
7,64008,จิรา,20.000,หญิง,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.000000,2024-02-13
8,64009,ชนาธิป,23.000,ชาย,ศิลปศาสตร์,3.340000,163.000000,55.000000,22.000000,2024-01-05
9,64010,ดารา,21.000,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.000000,28.000000,2024-01-17
10,64011,ธีระ,20.875,ชาย,วิทยาศาสตร์,3.780000,167.684211,68.000000,21.388889,2023-12-27
11,64012,นภา,22.000,ชาย,วิทยาศาสตร์,3.246111,171.000000,63.611111,16.000000,2024-02-11
12,64013,บุญมี,20.000,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.000000,24.000000,2024-01-06
13,64014,ปรีชา,21.000,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.000000,19.000000,2024-01-28
14,64015,พิมพ์,22.000,หญิง,วิทยาศาสตร์,3.670000,162.000000,56.000000,26.000000,2024-01-09
15,64016,ภูมิ,19.000,ชาย,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.000000,2024-02-02
16,64017,มานี,20.000,หญิง,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.000000,2024-01-11
17,64018,ยุพา,21.000,หญิง,วิทยาศาสตร์,3.230000,161.000000,50.000000,27.000000,2024-02-12
18,64019,รัตนา,20.875,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,21.388889,2024-01-26
19,64020,ลัดดา,22.000,ชาย,วิทยาศาสตร์,3.450000,168.000000,64.000000,23.000000,2024-01-12

# **4.2**

In [51]:
registration_data = df.copy()

registration_data['วันที่ลงทะเบียน'] = pd.to_datetime(registration_data['วันที่ลงทะเบียน'])

daily_registrations = registration_data.groupby(registration_data['วันที่ลงทะเบียน'].dt.date).size().reset_index(name='จำนวนนักศึกษาที่ลงทะเบียน')

print("จำนวนนักศึกษาที่ลงทะเบียนในแต่ละวัน:")
print(daily_registrations)

จำนวนนักศึกษาที่ลงทะเบียนในแต่ละวัน:
   วันที่ลงทะเบียน  จำนวนนักศึกษาที่ลงทะเบียน
0       2023-12-17                          2
1       2023-12-27                          1
2       2024-01-05                          1
3       2024-01-06                          1
4       2024-01-08                          1
5       2024-01-09                          1
6       2024-01-11                          1
7       2024-01-12                          1
8       2024-01-14                          1
9       2024-01-17                          1
10      2024-01-22                          1
11      2024-01-26                          1
12      2024-01-28                          2
13      2024-02-02                          1
14      2024-02-06                          1
15      2024-02-11                          1
16      2024-02-12                          1
17      2024-02-13                          1

# **4.3**

In [52]:
df['BMI'] = df['น้ำหนัก_kg'] / (df['ส่วนสูง_cm']/100)**2
df['สุขภาพ'] = pd.cut(df['BMI'],
                                   bins=[0, 18.5, 25, 30, 100],
                                   labels=['ผอม', 'ปกติ', 'อ้วน', 'อ้วนมาก'])

print(df[['ชื่อ', 'BMI', 'สุขภาพ']])

        ชื่อ        BMI สุขภาพ
0      สมชาย  22.491349   ปกติ
1     สมหญิง  21.303949   ปกติ
2        NaN  20.770975   ปกติ
3   สมศักดิ์  24.801587   ปกติ
4       สมใจ  20.312500   ปกติ
5      กานต์  25.351541   อ้วน
6      กิตติ  19.227688   ปกติ
7       จิรา  25.308642   อ้วน
8     ชนาธิป  20.700817   ปกติ
9       ดารา  21.513859   ปกติ
10      ธีระ  24.183802   ปกติ
11       นภา  21.754082   ปกติ
12     บุญมี  25.209201   อ้วน
13     ปรีชา  20.077335   ปกติ
14     พิมพ์  21.338211   ปกติ
15      ภูมิ  26.061679   อ้วน
16      มานี  22.499637   ปกติ
17      ยุพา  19.289379   ปกติ
18     รัตนา  25.102391   อ้วน
19     ลัดดา  22.675737   ปกติ